-- Cleanup script to remove existing gists with mismatched images
-- Run this in Supabase SQL Editor after deploying the migration and updated functions
-- This ensures all future gists respect the strict 1:1 mapping

-- Step 1: Delete all existing gists (they may have mismatched images)
-- WARNING: This will delete all gists. They will be regenerated by auto-generate-gists-v2
DELETE FROM public.gists;

-- Step 2: Reset processed flag on raw_trends so they can be regenerated
UPDATE public.raw_trends SET processed = false;

-- Step 3: Verify the cleanup
SELECT 
  COUNT(*) as remaining_gists,
  COUNT(DISTINCT raw_trend_id) as unique_raw_trend_ids
FROM public.gists;

-- Expected: remaining_gists = 0

-- Step 4: Verify raw_trends are ready for regeneration
SELECT 
  COUNT(*) as unprocessed_trends,
  COUNT(CASE WHEN image_url IS NOT NULL THEN 1 END) as trends_with_images
FROM public.raw_trends
WHERE processed = false;

-- After running this:
-- 1. Wait for auto-generate-gists-v2 cron job to run (or trigger manually)
-- 2. All new gists will have proper raw_trend_id linking
-- 3. Images will match headlines/content from the same raw_trend row

